title: <p align="center"> Hemachandar Nagarajan </p>

logo: "/images/image.PNG?raw=true"

description:
  <p align="center">
  <a href="mailto:chandar13@gmail.com">Email</a> |
  <a href="/resume">Resume</a> |
  <a href="https://www.linkedin.com/in/hemachandarn/">LinkedIn</a> |
  <a href="https://github.com/HemachandarN">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MS degree in Business Analytics at Drexel University and will have graduated by March 2021.
  <br><br>
  </p>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
