title: <p align="center"> Hemachandar Nagarajan </p>

logo: "/images/image.PNG?raw=true"

description:
  <p align="center">
  <a href="mailto:chandar13@gmail.com">Email</a> |
  <a href="/resume">Resume</a> |
  <a href="https://www.linkedin.com/in/hemachandarn/">LinkedIn</a> |
  <a href="https://github.com/HemachandarN">GitHub</a>
  </p>
  
  <p align="justify">
  Data scientist with over 3 years of experience in Data Science and Business Intelligence. Skilled at transforming data into highly valuable insights by harnessing analytics and machine learning. Project manager and team leader in a dynamic technology landscape. Track record of having delivered projects in healthcare, pharmaceutics, food manufacturing, and technology verticals.
  <br><br>
  </p>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
